base_url = "https://chiwork-aidisclosure.github.io"
compile_sass = true
build_search_index = false
generate_feeds = false
minify_html = true

[markdown]
highlight_code = false

[extra]
footer_text = false #"This website is built using the [Academic Workshop](http://github.com/aterenin/academic-workshop/) theme."
title = {tagline = "A Workshop @ The Symposium on Human-Computer Interaction for Work (CHIWORK)", title = "Navigating Generative AI Disclosure, Ownership, and Accountability in Co-Creative Domains", subtitles = ["June 23, 2025, 9AM - 1PM CEST", "Hybrid (Online & In-person at Amsterdam, The Netherlands)"]}
banner = {extension = "png", size = "fixed", fade = false}
buttons = [{name = "Home", url = "/"},{name = "Program", url = "/program"}] # creates a list of buttons displayed in order, with links to the URLs
image = {resize = 400, ext = '.jpg'}
list_page_limit = 10
header_pages = [{name = "Home", url = "/#home"},{name = "Design", url = "/#design"}]
enable_target_blank = true