name = "CHIWORK Workshop"
description = "Navigating Generative AI Disclosure, Ownership, and Accountability in Co-Creative Domains"
license = "MIT"
homepage = "chiwork-aidisclosure.github.io"
min_version = "0.1.0"

[extra]
footer_text = "This website is built using [Zola](https://www.getzola.org) and the [Academic Workshop](http://github.com/aterenin/academic-workshop/) theme."
image = {resize = 400, ext = '.jpg'}
list_page_limit = 10

[author]
name = "TBD-name"
homepage = "TBD-homepage"
