name = "CHIWORK Workshop"
description = "CHIWORK Workshop page"
license = "MIT"
min_version = "0.1.0"


[extra]
footer_text = "This website is built using [Zola](https://www.getzola.org) and the [Academic Workshop](http://github.com/aterenin/academic-workshop/) theme."
image = {resize = 400, ext = '.jpg'}
list_page_limit = 10
